name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master  # Voeg master toe voor het geval dat de standaard branch naam anders is

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install dependencies
        run: |
          npm ci
          npm install react-router-dom @types/react-router-dom firebase
        
      - name: Debug directory
        run: |
          echo "Files in src directory:"
          ls -la src/
          echo "Files in src/components directory:"
          ls -la src/components/
          echo "Files in src/context directory:"
          ls -la src/context/
          echo "Files in public directory:"
          ls -la public/
        
      - name: Build project
        run: npm run build
        env:
          CI: false  # This prevents treating warnings as errors
          
      - name: Create .nojekyll file to bypass Jekyll
        run: touch build/.nojekyll
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build  # The folder the action should deploy
          branch: gh-pages  # The branch to deploy to 